### PR TITLE
#74 Fix UDT replication fail

### LINKED ISSUE #74: UDT replication fails when one field is being set and others are already not-null in the database
After applying this modification to the `test_udt_fields_update`:

```diff
diff --git a/scylla-cdc-replicator/src/replication_tests.rs b/scylla-cdc-replicator/src/replication_tests.rs
index 7755666..44e9de1 100644
--- a/scylla-cdc-replicator/src/replication_tests.rs
+++ b/scylla-cdc-replicator/src/replication_tests.rs
@@ -970,6 +970,7 @@ mod tests {
         let operations = vec![
             "INSERT INTO TEST_UDT_ELEMENTS_UPDATE (pk, ck, v) VALUES (0, 1, {int_val: 1})",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = 2 WHERE pk = 0 AND ck = 1",
+            "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.bool_val = true WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = 5, v.bool_val = null WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = null, v.bool_val = false WHERE pk = 0 AND ck = 1",
         ];
```

...the test fails after the newly added query:

```
---- replication_tests::tests::test_udt_fields_update stdout ----
unique_name: test_rust_1650962436_30
unique_name: test_rust_1650962436_31
Replication test for table TEST_UDT_ELEMENTS_UPDATE failed.
Failure reason: Row 1 is not equal in both tables.
ORIGINAL TABLE:
Row 1: [Some(Int(0)), Some(Int(1)), Some(UserDefinedType { keyspace: "test_rust_1650962436_30", type_name: "ut", fields: [("int_val", Some(Int(2))), ("bool_val", Some(Boolean(true)))] })]
REPLICATED TABLE:
Row 1: [Some(Int(0)), Some(Int(1)), Some(UserDefinedType { keyspace: "test_rust_1650962436_31", type_name: "ut", fields: [("int_val", None), ("bool_val", Some(Boolean(true)))] })]
thread 'replication_tests::tests::test_udt_fields_update' panicked at 'explicit panic', scylla-cdc-replicator/src/replication_tests.rs:219:9
```

### PR DESCRIPTION
**Pull request by Ponewor**
Resolves #74

### CODE REVIEW

**Comment by Ponewor** [comment]
@piodul

**Review by piodul — CHANGES_REQUESTED** [review]

File: scylla-cdc-replicator/src/replicator_consumer.rs [hunk 1]
```diff
@@ -525,52 +499,23 @@ impl ReplicatorConsumer {
...
-                .map(|deleted_idx| {
-                    let idx = deleted_idx.as_smallint().unwrap();
-                    let (udt_fields_by_id, _) = udt_fields.get(idx as usize).unwrap();
-                    format!("{}.{} = null", column_name, udt_fields_by_id)
-                })
-                .join(",");
-
-            let values_for_update = &mut values_for_update.to_vec();
-            values_for_update.remove(1);
+        let value = data.get_value(column_name).as_ref().unwrap();
```
Comment (piodul) [inline scylla-cdc-replicator/src/replicator_consumer.rs:502]: The `test_udt_fields_update` test fails when I add another column and try to update it.

```diff
@@ -848,7 +848,7 @@ mod tests {
             name: "TEST_UDT_ELEMENTS_UPDATE".to_string(),
             partition_key: vec![("pk", "int")],
             clustering_key: vec![("ck", "int")],
-            other_columns: vec![("v", "ut")],
+            other_columns: vec![("v", "ut"), ("dummy", "int")],
         };
 
         let udt_schemas = vec![TestUDTSchema {
@@ -864,6 +864,7 @@ mod tests {
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = null, v.bool_val = false WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = 5 WHERE pk = 0 AND ck = 1",
             "UPDATE TEST_UDT_ELEMENTS_UPDATE SET v.int_val = null WHERE pk = 0 AND ck = 1",
+            "UPDATE TEST_UDT_ELEMENTS_UPDATE SET dummy = 1 WHERE pk = 0 AND ck = 1",
         ];
 
         test_replication_with_udt(schema, udt_schemas, operations)
```
```
failures:

---- replication_tests::tests::test_udt_fields_update stdout ----
unique_name: test_rust_1651469149_7
unique_name: test_rust_1651469150_39
thread 'replication_tests::tests::test_udt_fields_update' panicked at 'called `Option::unwrap()` on a `None` value', scylla-cdc-replicator/src/replicator_consumer.rs:502:58
```

`cdc$deleted_x == false || cdc$deleted_x == null` does not imply that `x` column is not-null. If the column `x` was unaffected in the original operation, then both `x` and `cdc$deleted_x` will be null/false - so you can't just unwrap here.

**Review by piodul — CHANGES_REQUESTED** [review]

**Review by piodul — APPROVED** [review]
Looks good, but I would appreciate a regression test against the issue with the logic not working properly when the column type was not updated in the operation. Let's follow up with a test which adds a table with multiple columns of different types and, in each operation, updates only one column.
